### ISSUE TITLE
Szenzorok elhelyezése az autón

### ISSUE THREAD

**Issue by jozdavab** [SzFMV2021-Osz/AutomatedCar-A#16]
1 db, a szélvédő mögé elhelyezett kamera 
1 db, az autó első lökhárítója mögött elhelyezett radar szenzor

**Comment by pintergreg** [comment]
> See userstory for more details

A user story-t be lehet hivatkozni. Szőrszálhasogatásnak tűnik legyen egyértelmű, hogy melyikre (`#2`). #2
